// Code generated by entc, DO NOT EDIT.

package menugroup

const (
	// Label holds the string label denoting the menugroup type in the database.
	Label = "menugroup"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldGroup holds the string denoting the group field in the database.
	FieldGroup = "group"

	// EdgeMenus holds the string denoting the menus edge name in mutations.
	EdgeMenus = "menus"

	// Table holds the table name of the menugroup in the database.
	Table = "menugroups"
	// MenusTable is the table the holds the menus relation/edge.
	MenusTable = "menus"
	// MenusInverseTable is the table name for the Menu entity.
	// It exists in this package in order to avoid circular dependency with the "menu" package.
	MenusInverseTable = "menus"
	// MenusColumn is the table column denoting the menus relation/edge.
	MenusColumn = "group_id"
)

// Columns holds all SQL columns for menugroup fields.
var Columns = []string{
	FieldID,
	FieldGroup,
}
