// Code generated by entc, DO NOT EDIT.

package predicate

import (
	"github.com/facebookincubator/ent/dialect/sql"
)

// Menu is the predicate function for menu builders.
type Menu func(*sql.Selector)

// Menugroup is the predicate function for menugroup builders.
type Menugroup func(*sql.Selector)

// Menutype is the predicate function for menutype builders.
type Menutype func(*sql.Selector)

// User is the predicate function for user builders.
type User func(*sql.Selector)
