// Code generated by entc, DO NOT EDIT.

package menutype

const (
	// Label holds the string label denoting the menutype type in the database.
	Label = "menutype"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldType holds the string denoting the type field in the database.
	FieldType = "type"

	// EdgeMenus holds the string denoting the menus edge name in mutations.
	EdgeMenus = "menus"

	// Table holds the table name of the menutype in the database.
	Table = "menutypes"
	// MenusTable is the table the holds the menus relation/edge.
	MenusTable = "menus"
	// MenusInverseTable is the table name for the Menu entity.
	// It exists in this package in order to avoid circular dependency with the "menu" package.
	MenusInverseTable = "menus"
	// MenusColumn is the table column denoting the menus relation/edge.
	MenusColumn = "type_id"
)

// Columns holds all SQL columns for menutype fields.
var Columns = []string{
	FieldID,
	FieldType,
}
