/* tslint:disable */
/* eslint-disable */
/**
 * SUT SA Example API Menu
 * This is a sample server for SUT SE 2563
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@swagger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    EntMenuEdges,
    EntMenuEdgesFromJSON,
    EntMenuEdgesFromJSONTyped,
    EntMenuEdgesToJSON,
} from './';

/**
 * 
 * @export
 * @interface EntMenu
 */
export interface EntMenu {
    /**
     * AddedTime holds the value of the "added_time" field.
     * @type {string}
     * @memberof EntMenu
     */
    addedTime?: string;
    /**
     * Calories holds the value of the "calories" field.
     * @type {number}
     * @memberof EntMenu
     */
    calories?: number;
    /**
     * 
     * @type {EntMenuEdges}
     * @memberof EntMenu
     */
    edges?: EntMenuEdges;
    /**
     * ID of the ent.
     * @type {number}
     * @memberof EntMenu
     */
    id?: number;
    /**
     * Ingredient holds the value of the "ingredient" field.
     * @type {string}
     * @memberof EntMenu
     */
    ingredient?: string;
    /**
     * Menuname holds the value of the "menuname" field.
     * @type {string}
     * @memberof EntMenu
     */
    menuname?: string;
}

export function EntMenuFromJSON(json: any): EntMenu {
    return EntMenuFromJSONTyped(json, false);
}

export function EntMenuFromJSONTyped(json: any, ignoreDiscriminator: boolean): EntMenu {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'addedTime': !exists(json, 'added_time') ? undefined : json['added_time'],
        'calories': !exists(json, 'calories') ? undefined : json['calories'],
        'edges': !exists(json, 'edges') ? undefined : EntMenuEdgesFromJSON(json['edges']),
        'id': !exists(json, 'id') ? undefined : json['id'],
        'ingredient': !exists(json, 'ingredient') ? undefined : json['ingredient'],
        'menuname': !exists(json, 'menuname') ? undefined : json['menuname'],
    };
}

export function EntMenuToJSON(value?: EntMenu | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'added_time': value.addedTime,
        'calories': value.calories,
        'edges': EntMenuEdgesToJSON(value.edges),
        'id': value.id,
        'ingredient': value.ingredient,
        'menuname': value.menuname,
    };
}


