// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"

	"github.com/facebookincubator/ent/dialect/sql"
	"github.com/facebookincubator/ent/dialect/sql/sqlgraph"
	"github.com/facebookincubator/ent/schema/field"
	"github.com/pomea/app/ent/menu"
	"github.com/pomea/app/ent/menugroup"
	"github.com/pomea/app/ent/predicate"
)

// MenugroupUpdate is the builder for updating Menugroup entities.
type MenugroupUpdate struct {
	config
	hooks      []Hook
	mutation   *MenugroupMutation
	predicates []predicate.Menugroup
}

// Where adds a new predicate for the builder.
func (mu *MenugroupUpdate) Where(ps ...predicate.Menugroup) *MenugroupUpdate {
	mu.predicates = append(mu.predicates, ps...)
	return mu
}

// SetGroup sets the group field.
func (mu *MenugroupUpdate) SetGroup(s string) *MenugroupUpdate {
	mu.mutation.SetGroup(s)
	return mu
}

// AddMenuIDs adds the menus edge to Menu by ids.
func (mu *MenugroupUpdate) AddMenuIDs(ids ...int) *MenugroupUpdate {
	mu.mutation.AddMenuIDs(ids...)
	return mu
}

// AddMenus adds the menus edges to Menu.
func (mu *MenugroupUpdate) AddMenus(m ...*Menu) *MenugroupUpdate {
	ids := make([]int, len(m))
	for i := range m {
		ids[i] = m[i].ID
	}
	return mu.AddMenuIDs(ids...)
}

// Mutation returns the MenugroupMutation object of the builder.
func (mu *MenugroupUpdate) Mutation() *MenugroupMutation {
	return mu.mutation
}

// RemoveMenuIDs removes the menus edge to Menu by ids.
func (mu *MenugroupUpdate) RemoveMenuIDs(ids ...int) *MenugroupUpdate {
	mu.mutation.RemoveMenuIDs(ids...)
	return mu
}

// RemoveMenus removes menus edges to Menu.
func (mu *MenugroupUpdate) RemoveMenus(m ...*Menu) *MenugroupUpdate {
	ids := make([]int, len(m))
	for i := range m {
		ids[i] = m[i].ID
	}
	return mu.RemoveMenuIDs(ids...)
}

// Save executes the query and returns the number of rows/vertices matched by this operation.
func (mu *MenugroupUpdate) Save(ctx context.Context) (int, error) {

	var (
		err      error
		affected int
	)
	if len(mu.hooks) == 0 {
		affected, err = mu.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*MenugroupMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			mu.mutation = mutation
			affected, err = mu.sqlSave(ctx)
			mutation.done = true
			return affected, err
		})
		for i := len(mu.hooks) - 1; i >= 0; i-- {
			mut = mu.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, mu.mutation); err != nil {
			return 0, err
		}
	}
	return affected, err
}

// SaveX is like Save, but panics if an error occurs.
func (mu *MenugroupUpdate) SaveX(ctx context.Context) int {
	affected, err := mu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (mu *MenugroupUpdate) Exec(ctx context.Context) error {
	_, err := mu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (mu *MenugroupUpdate) ExecX(ctx context.Context) {
	if err := mu.Exec(ctx); err != nil {
		panic(err)
	}
}

func (mu *MenugroupUpdate) sqlSave(ctx context.Context) (n int, err error) {
	_spec := &sqlgraph.UpdateSpec{
		Node: &sqlgraph.NodeSpec{
			Table:   menugroup.Table,
			Columns: menugroup.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: menugroup.FieldID,
			},
		},
	}
	if ps := mu.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := mu.mutation.Group(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: menugroup.FieldGroup,
		})
	}
	if nodes := mu.mutation.RemovedMenusIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   menugroup.MenusTable,
			Columns: []string{menugroup.MenusColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: menu.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := mu.mutation.MenusIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   menugroup.MenusTable,
			Columns: []string{menugroup.MenusColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: menu.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, mu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{menugroup.Label}
		} else if cerr, ok := isSQLConstraintError(err); ok {
			err = cerr
		}
		return 0, err
	}
	return n, nil
}

// MenugroupUpdateOne is the builder for updating a single Menugroup entity.
type MenugroupUpdateOne struct {
	config
	hooks    []Hook
	mutation *MenugroupMutation
}

// SetGroup sets the group field.
func (muo *MenugroupUpdateOne) SetGroup(s string) *MenugroupUpdateOne {
	muo.mutation.SetGroup(s)
	return muo
}

// AddMenuIDs adds the menus edge to Menu by ids.
func (muo *MenugroupUpdateOne) AddMenuIDs(ids ...int) *MenugroupUpdateOne {
	muo.mutation.AddMenuIDs(ids...)
	return muo
}

// AddMenus adds the menus edges to Menu.
func (muo *MenugroupUpdateOne) AddMenus(m ...*Menu) *MenugroupUpdateOne {
	ids := make([]int, len(m))
	for i := range m {
		ids[i] = m[i].ID
	}
	return muo.AddMenuIDs(ids...)
}

// Mutation returns the MenugroupMutation object of the builder.
func (muo *MenugroupUpdateOne) Mutation() *MenugroupMutation {
	return muo.mutation
}

// RemoveMenuIDs removes the menus edge to Menu by ids.
func (muo *MenugroupUpdateOne) RemoveMenuIDs(ids ...int) *MenugroupUpdateOne {
	muo.mutation.RemoveMenuIDs(ids...)
	return muo
}

// RemoveMenus removes menus edges to Menu.
func (muo *MenugroupUpdateOne) RemoveMenus(m ...*Menu) *MenugroupUpdateOne {
	ids := make([]int, len(m))
	for i := range m {
		ids[i] = m[i].ID
	}
	return muo.RemoveMenuIDs(ids...)
}

// Save executes the query and returns the updated entity.
func (muo *MenugroupUpdateOne) Save(ctx context.Context) (*Menugroup, error) {

	var (
		err  error
		node *Menugroup
	)
	if len(muo.hooks) == 0 {
		node, err = muo.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*MenugroupMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			muo.mutation = mutation
			node, err = muo.sqlSave(ctx)
			mutation.done = true
			return node, err
		})
		for i := len(muo.hooks) - 1; i >= 0; i-- {
			mut = muo.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, muo.mutation); err != nil {
			return nil, err
		}
	}
	return node, err
}

// SaveX is like Save, but panics if an error occurs.
func (muo *MenugroupUpdateOne) SaveX(ctx context.Context) *Menugroup {
	m, err := muo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return m
}

// Exec executes the query on the entity.
func (muo *MenugroupUpdateOne) Exec(ctx context.Context) error {
	_, err := muo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (muo *MenugroupUpdateOne) ExecX(ctx context.Context) {
	if err := muo.Exec(ctx); err != nil {
		panic(err)
	}
}

func (muo *MenugroupUpdateOne) sqlSave(ctx context.Context) (m *Menugroup, err error) {
	_spec := &sqlgraph.UpdateSpec{
		Node: &sqlgraph.NodeSpec{
			Table:   menugroup.Table,
			Columns: menugroup.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: menugroup.FieldID,
			},
		},
	}
	id, ok := muo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "ID", err: fmt.Errorf("missing Menugroup.ID for update")}
	}
	_spec.Node.ID.Value = id
	if value, ok := muo.mutation.Group(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: menugroup.FieldGroup,
		})
	}
	if nodes := muo.mutation.RemovedMenusIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   menugroup.MenusTable,
			Columns: []string{menugroup.MenusColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: menu.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := muo.mutation.MenusIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   menugroup.MenusTable,
			Columns: []string{menugroup.MenusColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: menu.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	m = &Menugroup{config: muo.config}
	_spec.Assign = m.assignValues
	_spec.ScanValues = m.scanValues()
	if err = sqlgraph.UpdateNode(ctx, muo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{menugroup.Label}
		} else if cerr, ok := isSQLConstraintError(err); ok {
			err = cerr
		}
		return nil, err
	}
	return m, nil
}
