// Code generated by entc, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"

	"github.com/facebookincubator/ent/dialect/sql"
	"github.com/pomea/app/ent/menugroup"
)

// Menugroup is the model entity for the Menugroup schema.
type Menugroup struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// Group holds the value of the "group" field.
	Group string `json:"group,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the MenugroupQuery when eager-loading is set.
	Edges MenugroupEdges `json:"edges"`
}

// MenugroupEdges holds the relations/edges for other nodes in the graph.
type MenugroupEdges struct {
	// Menus holds the value of the menus edge.
	Menus []*Menu
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// MenusOrErr returns the Menus value or an error if the edge
// was not loaded in eager-loading.
func (e MenugroupEdges) MenusOrErr() ([]*Menu, error) {
	if e.loadedTypes[0] {
		return e.Menus, nil
	}
	return nil, &NotLoadedError{edge: "menus"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Menugroup) scanValues() []interface{} {
	return []interface{}{
		&sql.NullInt64{},  // id
		&sql.NullString{}, // group
	}
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Menugroup fields.
func (m *Menugroup) assignValues(values ...interface{}) error {
	if m, n := len(values), len(menugroup.Columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	value, ok := values[0].(*sql.NullInt64)
	if !ok {
		return fmt.Errorf("unexpected type %T for field id", value)
	}
	m.ID = int(value.Int64)
	values = values[1:]
	if value, ok := values[0].(*sql.NullString); !ok {
		return fmt.Errorf("unexpected type %T for field group", values[0])
	} else if value.Valid {
		m.Group = value.String
	}
	return nil
}

// QueryMenus queries the menus edge of the Menugroup.
func (m *Menugroup) QueryMenus() *MenuQuery {
	return (&MenugroupClient{config: m.config}).QueryMenus(m)
}

// Update returns a builder for updating this Menugroup.
// Note that, you need to call Menugroup.Unwrap() before calling this method, if this Menugroup
// was returned from a transaction, and the transaction was committed or rolled back.
func (m *Menugroup) Update() *MenugroupUpdateOne {
	return (&MenugroupClient{config: m.config}).UpdateOne(m)
}

// Unwrap unwraps the entity that was returned from a transaction after it was closed,
// so that all next queries will be executed through the driver which created the transaction.
func (m *Menugroup) Unwrap() *Menugroup {
	tx, ok := m.config.driver.(*txDriver)
	if !ok {
		panic("ent: Menugroup is not a transactional entity")
	}
	m.config.driver = tx.drv
	return m
}

// String implements the fmt.Stringer.
func (m *Menugroup) String() string {
	var builder strings.Builder
	builder.WriteString("Menugroup(")
	builder.WriteString(fmt.Sprintf("id=%v", m.ID))
	builder.WriteString(", group=")
	builder.WriteString(m.Group)
	builder.WriteByte(')')
	return builder.String()
}

// Menugroups is a parsable slice of Menugroup.
type Menugroups []*Menugroup

func (m Menugroups) config(cfg config) {
	for _i := range m {
		m[_i].config = cfg
	}
}
